### ISSUE TITLE
Add an improved `write_xlsx()` function

### ISSUE THREAD

**Issue by elipousson** [elipousson/openxlsx2Extras#3]
Ideas for improvements:

- [X] Validate file extension (avoid issue w/ xslx or similar typos)
- [X] ~Moving column aliases into a row above the table header row~ (move to #6)
- [ ] ~More opinionated default formatting (with options to override defaults globally)~ (move to #6)
- [x] ~Allow a named list of data frames as an input~ (already supported!)
- [X] ~Improved handling for sf objects as inputs (either dropping geometry or converting to a WKT column or coordinate columns)~ (move to #6)
- [ ] ~Allow gt objects as inputs - see https://github.com/yannsay/gtopenxlsx~ (move to #4)
- [x] Invisibly return x (not a workbook object) to allow use in middle of pipeline

Related projects:

- https://github.com/ddotta/tablexlsx

**Comment by elipousson** [comment]
Started here: https://github.com/elipousson/openxlsx2Extras/blob/main/R/wb_save.R

**Comment by JanMarvin** [comment]
>     * Allow a named list of data frames as an input

Do you mean this?
``` r
library(openxlsx2)
ll <- list(mtcars = mtcars, iris = iris)
write_xlsx(x = ll)$get_sheet_names()
#>   mtcars     iris 
#> "mtcars"   "iris"
```

To the list of further related projects:
* `flexlsx`: https://github.com/pteridin/flexlsx (allows exporting `flextable` objects via `openxlsx2`)
* `a11ytables2`: https://github.com/matt-dray/a11ytables2 (not sure about the state of development, but the aim is to create formatted spreadsheets from R)

**Comment by elipousson** [comment]
Thanks, @JanMarvin! I created #6 to organize features for a `wb_add_data()` wrapper function separately from this issue.

Would file extension validation for inputs and output files be a feature you may be interested for `{openxlsx2}`? I somewhat regularly mix up "xlsx" and "xslx" when writing out a file name. I also tried to load a Word document and the error message could be a little more direct.

**Comment by JanMarvin** [comment]
I always fear that such well ment features annoy the user in dozens of different ways. If the user wants to save as xslx, then why not?
But we can always improve messages, documentation and the likes and if the file name checker doesn’t bring new dependencies and isn’t screaming at me all the time, we could at least give it a try.
